services: 
  postgres:
    image: postgres:17-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=dev
      - POSTGRES_DB=selfstudy_db
  app:
    build: .
    ports:
      - 8000:8000
    environment:
      - POSTGRES_CONNECTION=postgresql://dev:password@postgres/selfstudy_db
volumes:
  postgres:
    driver: local
