services: 
  postgres:
    image: postgres:17-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=dev
      - POSTGRES_DB=selfstudy_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      retries: 5
      start_period: 30s
      timeout: 10s
  app:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
    ports:
      - 8000:8000
    environment:
      - DATABSE_URI=postgresql://dev:password@postgres/selfstudy_db
      - JWT_SECRET_KEY=supersecret
volumes:
  postgres:
    driver: local
